## THIS FILE WAS GENERATED BY AN AUTOMATED RUBY TASK!
## ANY MODIFICATIONS MADE TO THIS FILE MAY BE OVERWRITTEN!

class_name PlayingCardCodex
extends Node

enum ID {
    NULL_MINION = 0,
    MUSHROOM_MAN = 1,
    POT_OF_LINGUINE = 2,
    SPIKY_MUSHROOM_MAN = 3,
    TINY_TURTLE = 4,
    ZANY_ZOMBIE = 5,
    TRIANGLE_TROOPER = 6,
    SERGEANT_SQUARE = 7,
    RHOMBUS_RANGER = 8,
    PENTAGON_PROTECTOR = 9,
    CAPTAIN_CIRCLE = 10,
    RAVIOLI_RUNT = 11,
    BUSY_BEE = 12,
    CORNY_ACORN = 13,
    GOLDEN_ACORN = 14,
    ROBOT_MITE = 15,
    MEATBALL_MAN = 16,
    UNPAID_INTERN = 17,
    BABY_CLOWN = 18,
    SPAGHETTI_MONSTER = 19,
    PENNE_PIKEMAN = 20,
    PENNE_SHARPSHOOTER = 21,
    TEMP_WORKER = 22,
    IT_WORKER = 23,
    CONTRACTOR = 24,
    MIDDLE_MANAGER = 25,
    TODDLER_CLOWN = 26,
    ROBOT_ASSISTANT = 27,
    DEATH_CYBORG = 28,
    PASTA_POWER = 29,
    HIRED_NINJA = 30,
    ANCIENT_SCROLL = 31,
    SPIKY_TURTLE = 32,
    CHICKEN = 33,
    PIG = 34,
    GIANT_PIG = 35,
    METAL_SPIDER = 36,
    NINJA_ASSASSIN = 37,
    MASKED_TURTLE = 38,
    UNDEAD_PIG = 39,
    QUEEN_BEE = 40,
    CATACOMB_CHARMER = 41,
    MIRROR_CRYSTAL = 42,
    RAIN_DANCE = 43,
    REINFORCED_SHELL = 44,
    POWER_SURGE = 45,
    WORKER_BEE = 46,
    BEEHIVE = 47,
    FURIOUS_PHANTOM = 48,
    HONEY_JAR = 49,
    GRAVESTONE_POLISHING = 50,
    THE_INTERNET = 51,
    SPARE_BATTERY = 52,
    MILK_DELIVERY = 53,
    NUCLEAR_POWER_PLANT = 54,
    NUCLEAR_FUSION_PLANT = 55,
    SECOND_COURSE = 56,
    WITH_EXTRA_CHEESE = 57,
    COVER_OF_MOONLIGHT = 58,
    PLUMBERMAN = 59,
    DAMSEL_IN_DISTRESS = 60,
    KIDNAPPING_THE_PRESIDENT = 61,
    ZOMBEE = 62,
    MIMEDROID = 63,
    NINJA_MASTER = 64,
    MILITARY_ANDROID = 65,
    SPIKY_ACORN = 66,
    CORDYCEPS = 67,
    METAL_TURTLE = 68,
    SPIKY_METAL_TURTLE = 69,
    PLUMBERMANS_BROTHER = 70,
    KING_TURTLE = 71,
    STREET_MIME = 72,
    MIME_SUPERIOR = 73,
    FINAL_CLOWN = 74,
    METAL_SCORPION = 75,
    DISEMBODIED_SOUL = 76,
    NANOBOT_SWARM = 77,
    FOREVER_CLOWN = 78,
    SPIKY_MASKED_TURTLE = 79,
    MINIONMAN = 80,
    DR_BADGUY_DOOMCAKE = 81,
    FARMER_BLUE = 82,
    RHOMBICUBOCTAHEDRON = 83,
    HYPERCUBE_PRISON = 84,
    FLYING_BRICKMAN = 85,
    KING_CANNOLI = 86,
    RAVENMAN = 87,
    RAVENBOY = 88,
    RAVENGIRL = 89,
    SQUAREDUDE = 90,
    CIRCLEGIRL = 91,
    PRISMAN = 92,
    CALL_OF_ECTOPLASM = 93,
    CLUELESS_MAN = 94,
    WALL_GOLEM = 95,
    GRAVEYARD_DANCE = 96,
    VENOMATRIX = 97,
    COUNT_CARBONARA = 98,
    VITAMIN_CAPSULE = 99,
    TURKEY = 100,
    DUCK = 101,
    TURDUCKEN = 102,
    DR_MEGURUKU = 103,
    ULTIMATE_FUSION = 104,
    SPIRIT_FLUTE = 105,
    PET_COW = 106,
    MANDATORY_OVERTIME = 107,
    DESTINYS_SONG = 108,
    RED_TURTLE = 109,
    SPIKY_RED_TURTLE = 110,
    TREE_NYMPH = 111,
    FANCIFUL_FAIRY = 112,
    ICOSAKING = 113,
    TRUE_NINJA_MASTER = 114,
    THE_MASTERMIME = 115,
    DEATH = 116,
    NEEDLE_STRIKE = 117,
    BRISTLEGAZE = 118,
    BOILING_POT_OF_WATER = 119,
    LAST_STAND = 120,
    CIRCLE_OF_LIFE = 121,
    CIRCUS_MAKEUP = 122,
    HAY_BALES = 123,
    CURSED_TALISMAN = 124,
    GIGGLES_GALORE = 125,
    MILKMAN_MARAUDER = 126,
    MAXWELL_STERLING = 127,
    BARRY = 128,
    THE_DEVIL = 129,
    MYSTERY_BOX = 130,
    INFERNAL_IMP = 131,
    GREEDY_GOBLIN = 132,
    ANCIENT_DEMON = 133,
    AGARIC_TURTLE = 134,
    REPLACEABLE_PARTS = 135,
    PET_COWN = 136,
    LIBRARY_OF_ALEXANDRIA = 137,
    CLOWN_NOSE = 138,
    PACIFIER = 139,
    CHICK_INATOR = 140,
    BRAINWASHING_RAY = 141,
    NO_HONK_ZONE = 142,
    SILENT_CLOWN = 143,
    FOREMAN = 144,
    CULTIST = 145,
    BEEKEEPER = 146,
    GREENER_PASTURES = 147,
    SPIKY_SHELL = 148,
    SHELL_POLISHING = 149,
    BERRY = 150,
    CHRIS_COGSWORTH = 151,
    STINGER_SWARM = 152,
    HIVEMIND = 153,
    EXTENDED_WARRANTY = 154,
    NINJA_MASK = 155,
    LAUGHING_GAS = 156,
    INVASIVE_PARASITES = 157,
    METAL_CHICKEN = 158,
    DESTRUCTION_TANK = 159,
    WIMPY = 160,
    WIMPY_SMASH = 161,
    BULL_MARKET = 162,
    HYPERACTIVE_BEE = 163,
    GREEN_RANGER = 164,
    ICE_MOTH = 165,
    FORBIDDEN_FRUIT = 166,
    CYBERNETIC_ENHANCEMENT = 167,
    SHELL_SHIELD = 168,
    TOXIC_SPORES = 169,
    CIRCUS_TENT = 170,
    POISON_CLOUD = 171,
    POLLINATION = 172,
}

static func get_entity_script(n: int) -> GDScript:
    match n:
        ID.NULL_MINION:
            return load("res://card_game/playing_card/cards/null_minion.gd") as GDScript
        ID.MUSHROOM_MAN:
            return load("res://card_game/playing_card/cards/mushroom_man.gd") as GDScript
        ID.POT_OF_LINGUINE:
            return load("res://card_game/playing_card/cards/pot_of_linguine.gd") as GDScript
        ID.SPIKY_MUSHROOM_MAN:
            return load("res://card_game/playing_card/cards/spiky_mushroom_man.gd") as GDScript
        ID.TINY_TURTLE:
            return load("res://card_game/playing_card/cards/tiny_turtle.gd") as GDScript
        ID.ZANY_ZOMBIE:
            return load("res://card_game/playing_card/cards/zany_zombie.gd") as GDScript
        ID.TRIANGLE_TROOPER:
            return load("res://card_game/playing_card/cards/triangle_trooper.gd") as GDScript
        ID.SERGEANT_SQUARE:
            return load("res://card_game/playing_card/cards/sergeant_square.gd") as GDScript
        ID.RHOMBUS_RANGER:
            return load("res://card_game/playing_card/cards/rhombus_ranger.gd") as GDScript
        ID.PENTAGON_PROTECTOR:
            return load("res://card_game/playing_card/cards/pentagon_protector.gd") as GDScript
        ID.CAPTAIN_CIRCLE:
            return load("res://card_game/playing_card/cards/captain_circle.gd") as GDScript
        ID.RAVIOLI_RUNT:
            return load("res://card_game/playing_card/cards/ravioli_runt.gd") as GDScript
        ID.BUSY_BEE:
            return load("res://card_game/playing_card/cards/busy_bee.gd") as GDScript
        ID.CORNY_ACORN:
            return load("res://card_game/playing_card/cards/corny_acorn.gd") as GDScript
        ID.GOLDEN_ACORN:
            return load("res://card_game/playing_card/cards/golden_acorn.gd") as GDScript
        ID.ROBOT_MITE:
            return load("res://card_game/playing_card/cards/robot_mite.gd") as GDScript
        ID.MEATBALL_MAN:
            return load("res://card_game/playing_card/cards/meatball_man.gd") as GDScript
        ID.UNPAID_INTERN:
            return load("res://card_game/playing_card/cards/unpaid_intern.gd") as GDScript
        ID.BABY_CLOWN:
            return load("res://card_game/playing_card/cards/baby_clown.gd") as GDScript
        ID.SPAGHETTI_MONSTER:
            return load("res://card_game/playing_card/cards/spaghetti_monster.gd") as GDScript
        ID.PENNE_PIKEMAN:
            return load("res://card_game/playing_card/cards/penne_pikeman.gd") as GDScript
        ID.PENNE_SHARPSHOOTER:
            return load("res://card_game/playing_card/cards/penne_sharpshooter.gd") as GDScript
        ID.TEMP_WORKER:
            return load("res://card_game/playing_card/cards/temp_worker.gd") as GDScript
        ID.IT_WORKER:
            return load("res://card_game/playing_card/cards/it_worker.gd") as GDScript
        ID.CONTRACTOR:
            return load("res://card_game/playing_card/cards/contractor.gd") as GDScript
        ID.MIDDLE_MANAGER:
            return load("res://card_game/playing_card/cards/middle_manager.gd") as GDScript
        ID.TODDLER_CLOWN:
            return load("res://card_game/playing_card/cards/toddler_clown.gd") as GDScript
        ID.ROBOT_ASSISTANT:
            return load("res://card_game/playing_card/cards/robot_assistant.gd") as GDScript
        ID.DEATH_CYBORG:
            return load("res://card_game/playing_card/cards/death_cyborg.gd") as GDScript
        ID.PASTA_POWER:
            return load("res://card_game/playing_card/cards/pasta_power.gd") as GDScript
        ID.HIRED_NINJA:
            return load("res://card_game/playing_card/cards/hired_ninja.gd") as GDScript
        ID.ANCIENT_SCROLL:
            return load("res://card_game/playing_card/cards/ancient_scroll.gd") as GDScript
        ID.SPIKY_TURTLE:
            return load("res://card_game/playing_card/cards/spiky_turtle.gd") as GDScript
        ID.CHICKEN:
            return load("res://card_game/playing_card/cards/chicken.gd") as GDScript
        ID.PIG:
            return load("res://card_game/playing_card/cards/pig.gd") as GDScript
        ID.GIANT_PIG:
            return load("res://card_game/playing_card/cards/giant_pig.gd") as GDScript
        ID.METAL_SPIDER:
            return load("res://card_game/playing_card/cards/metal_spider.gd") as GDScript
        ID.NINJA_ASSASSIN:
            return load("res://card_game/playing_card/cards/ninja_assassin.gd") as GDScript
        ID.MASKED_TURTLE:
            return load("res://card_game/playing_card/cards/masked_turtle.gd") as GDScript
        ID.UNDEAD_PIG:
            return load("res://card_game/playing_card/cards/undead_pig.gd") as GDScript
        ID.QUEEN_BEE:
            return load("res://card_game/playing_card/cards/queen_bee.gd") as GDScript
        ID.CATACOMB_CHARMER:
            return load("res://card_game/playing_card/cards/catacomb_charmer.gd") as GDScript
        ID.MIRROR_CRYSTAL:
            return load("res://card_game/playing_card/cards/mirror_crystal.gd") as GDScript
        ID.RAIN_DANCE:
            return load("res://card_game/playing_card/cards/rain_dance.gd") as GDScript
        ID.REINFORCED_SHELL:
            return load("res://card_game/playing_card/cards/reinforced_shell.gd") as GDScript
        ID.POWER_SURGE:
            return load("res://card_game/playing_card/cards/power_surge.gd") as GDScript
        ID.WORKER_BEE:
            return load("res://card_game/playing_card/cards/worker_bee.gd") as GDScript
        ID.BEEHIVE:
            return load("res://card_game/playing_card/cards/beehive.gd") as GDScript
        ID.FURIOUS_PHANTOM:
            return load("res://card_game/playing_card/cards/furious_phantom.gd") as GDScript
        ID.HONEY_JAR:
            return load("res://card_game/playing_card/cards/honey_jar.gd") as GDScript
        ID.GRAVESTONE_POLISHING:
            return load("res://card_game/playing_card/cards/gravestone_polishing.gd") as GDScript
        ID.THE_INTERNET:
            return load("res://card_game/playing_card/cards/the_internet.gd") as GDScript
        ID.SPARE_BATTERY:
            return load("res://card_game/playing_card/cards/spare_battery.gd") as GDScript
        ID.MILK_DELIVERY:
            return load("res://card_game/playing_card/cards/milk_delivery.gd") as GDScript
        ID.NUCLEAR_POWER_PLANT:
            return load("res://card_game/playing_card/cards/nuclear_power_plant.gd") as GDScript
        ID.NUCLEAR_FUSION_PLANT:
            return load("res://card_game/playing_card/cards/nuclear_fusion_plant.gd") as GDScript
        ID.SECOND_COURSE:
            return load("res://card_game/playing_card/cards/second_course.gd") as GDScript
        ID.WITH_EXTRA_CHEESE:
            return load("res://card_game/playing_card/cards/with_extra_cheese.gd") as GDScript
        ID.COVER_OF_MOONLIGHT:
            return load("res://card_game/playing_card/cards/cover_of_moonlight.gd") as GDScript
        ID.PLUMBERMAN:
            return load("res://card_game/playing_card/cards/plumberman.gd") as GDScript
        ID.DAMSEL_IN_DISTRESS:
            return load("res://card_game/playing_card/cards/damsel_in_distress.gd") as GDScript
        ID.KIDNAPPING_THE_PRESIDENT:
            return load("res://card_game/playing_card/cards/kidnapping_the_president.gd") as GDScript
        ID.ZOMBEE:
            return load("res://card_game/playing_card/cards/zombee.gd") as GDScript
        ID.MIMEDROID:
            return load("res://card_game/playing_card/cards/mimedroid.gd") as GDScript
        ID.NINJA_MASTER:
            return load("res://card_game/playing_card/cards/ninja_master.gd") as GDScript
        ID.MILITARY_ANDROID:
            return load("res://card_game/playing_card/cards/military_android.gd") as GDScript
        ID.SPIKY_ACORN:
            return load("res://card_game/playing_card/cards/spiky_acorn.gd") as GDScript
        ID.CORDYCEPS:
            return load("res://card_game/playing_card/cards/cordyceps.gd") as GDScript
        ID.METAL_TURTLE:
            return load("res://card_game/playing_card/cards/metal_turtle.gd") as GDScript
        ID.SPIKY_METAL_TURTLE:
            return load("res://card_game/playing_card/cards/spiky_metal_turtle.gd") as GDScript
        ID.PLUMBERMANS_BROTHER:
            return load("res://card_game/playing_card/cards/plumbermans_brother.gd") as GDScript
        ID.KING_TURTLE:
            return load("res://card_game/playing_card/cards/king_turtle.gd") as GDScript
        ID.STREET_MIME:
            return load("res://card_game/playing_card/cards/street_mime.gd") as GDScript
        ID.MIME_SUPERIOR:
            return load("res://card_game/playing_card/cards/mime_superior.gd") as GDScript
        ID.FINAL_CLOWN:
            return load("res://card_game/playing_card/cards/final_clown.gd") as GDScript
        ID.METAL_SCORPION:
            return load("res://card_game/playing_card/cards/metal_scorpion.gd") as GDScript
        ID.DISEMBODIED_SOUL:
            return load("res://card_game/playing_card/cards/disembodied_soul.gd") as GDScript
        ID.NANOBOT_SWARM:
            return load("res://card_game/playing_card/cards/nanobot_swarm.gd") as GDScript
        ID.FOREVER_CLOWN:
            return load("res://card_game/playing_card/cards/forever_clown.gd") as GDScript
        ID.SPIKY_MASKED_TURTLE:
            return load("res://card_game/playing_card/cards/spiky_masked_turtle.gd") as GDScript
        ID.MINIONMAN:
            return load("res://card_game/playing_card/cards/minionman.gd") as GDScript
        ID.DR_BADGUY_DOOMCAKE:
            return load("res://card_game/playing_card/cards/dr_badguy_doomcake.gd") as GDScript
        ID.FARMER_BLUE:
            return load("res://card_game/playing_card/cards/farmer_blue.gd") as GDScript
        ID.RHOMBICUBOCTAHEDRON:
            return load("res://card_game/playing_card/cards/rhombicuboctahedron.gd") as GDScript
        ID.HYPERCUBE_PRISON:
            return load("res://card_game/playing_card/cards/hypercube_prison.gd") as GDScript
        ID.FLYING_BRICKMAN:
            return load("res://card_game/playing_card/cards/flying_brickman.gd") as GDScript
        ID.KING_CANNOLI:
            return load("res://card_game/playing_card/cards/king_cannoli.gd") as GDScript
        ID.RAVENMAN:
            return load("res://card_game/playing_card/cards/ravenman.gd") as GDScript
        ID.RAVENBOY:
            return load("res://card_game/playing_card/cards/ravenboy.gd") as GDScript
        ID.RAVENGIRL:
            return load("res://card_game/playing_card/cards/ravengirl.gd") as GDScript
        ID.SQUAREDUDE:
            return load("res://card_game/playing_card/cards/squaredude.gd") as GDScript
        ID.CIRCLEGIRL:
            return load("res://card_game/playing_card/cards/circlegirl.gd") as GDScript
        ID.PRISMAN:
            return load("res://card_game/playing_card/cards/prisman.gd") as GDScript
        ID.CALL_OF_ECTOPLASM:
            return load("res://card_game/playing_card/cards/call_of_ectoplasm.gd") as GDScript
        ID.CLUELESS_MAN:
            return load("res://card_game/playing_card/cards/clueless_man.gd") as GDScript
        ID.WALL_GOLEM:
            return load("res://card_game/playing_card/cards/wall_golem.gd") as GDScript
        ID.GRAVEYARD_DANCE:
            return load("res://card_game/playing_card/cards/graveyard_dance.gd") as GDScript
        ID.VENOMATRIX:
            return load("res://card_game/playing_card/cards/venomatrix.gd") as GDScript
        ID.COUNT_CARBONARA:
            return load("res://card_game/playing_card/cards/count_carbonara.gd") as GDScript
        ID.VITAMIN_CAPSULE:
            return load("res://card_game/playing_card/cards/vitamin_capsule.gd") as GDScript
        ID.TURKEY:
            return load("res://card_game/playing_card/cards/turkey.gd") as GDScript
        ID.DUCK:
            return load("res://card_game/playing_card/cards/duck.gd") as GDScript
        ID.TURDUCKEN:
            return load("res://card_game/playing_card/cards/turducken.gd") as GDScript
        ID.DR_MEGURUKU:
            return load("res://card_game/playing_card/cards/dr_meguruku.gd") as GDScript
        ID.ULTIMATE_FUSION:
            return load("res://card_game/playing_card/cards/ultimate_fusion.gd") as GDScript
        ID.SPIRIT_FLUTE:
            return load("res://card_game/playing_card/cards/spirit_flute.gd") as GDScript
        ID.PET_COW:
            return load("res://card_game/playing_card/cards/pet_cow.gd") as GDScript
        ID.MANDATORY_OVERTIME:
            return load("res://card_game/playing_card/cards/mandatory_overtime.gd") as GDScript
        ID.DESTINYS_SONG:
            return load("res://card_game/playing_card/cards/destinys_song.gd") as GDScript
        ID.RED_TURTLE:
            return load("res://card_game/playing_card/cards/red_turtle.gd") as GDScript
        ID.SPIKY_RED_TURTLE:
            return load("res://card_game/playing_card/cards/spiky_red_turtle.gd") as GDScript
        ID.TREE_NYMPH:
            return load("res://card_game/playing_card/cards/tree_nymph.gd") as GDScript
        ID.FANCIFUL_FAIRY:
            return load("res://card_game/playing_card/cards/fanciful_fairy.gd") as GDScript
        ID.ICOSAKING:
            return load("res://card_game/playing_card/cards/icosaking.gd") as GDScript
        ID.TRUE_NINJA_MASTER:
            return load("res://card_game/playing_card/cards/true_ninja_master.gd") as GDScript
        ID.THE_MASTERMIME:
            return load("res://card_game/playing_card/cards/the_mastermime.gd") as GDScript
        ID.DEATH:
            return load("res://card_game/playing_card/cards/death.gd") as GDScript
        ID.NEEDLE_STRIKE:
            return load("res://card_game/playing_card/cards/needle_strike.gd") as GDScript
        ID.BRISTLEGAZE:
            return load("res://card_game/playing_card/cards/bristlegaze.gd") as GDScript
        ID.BOILING_POT_OF_WATER:
            return load("res://card_game/playing_card/cards/boiling_pot_of_water.gd") as GDScript
        ID.LAST_STAND:
            return load("res://card_game/playing_card/cards/last_stand.gd") as GDScript
        ID.CIRCLE_OF_LIFE:
            return load("res://card_game/playing_card/cards/circle_of_life.gd") as GDScript
        ID.CIRCUS_MAKEUP:
            return load("res://card_game/playing_card/cards/circus_makeup.gd") as GDScript
        ID.HAY_BALES:
            return load("res://card_game/playing_card/cards/hay_bales.gd") as GDScript
        ID.CURSED_TALISMAN:
            return load("res://card_game/playing_card/cards/cursed_talisman.gd") as GDScript
        ID.GIGGLES_GALORE:
            return load("res://card_game/playing_card/cards/giggles_galore.gd") as GDScript
        ID.MILKMAN_MARAUDER:
            return load("res://card_game/playing_card/cards/milkman_marauder.gd") as GDScript
        ID.MAXWELL_STERLING:
            return load("res://card_game/playing_card/cards/maxwell_sterling.gd") as GDScript
        ID.BARRY:
            return load("res://card_game/playing_card/cards/barry.gd") as GDScript
        ID.THE_DEVIL:
            return load("res://card_game/playing_card/cards/the_devil.gd") as GDScript
        ID.MYSTERY_BOX:
            return load("res://card_game/playing_card/cards/mystery_box.gd") as GDScript
        ID.INFERNAL_IMP:
            return load("res://card_game/playing_card/cards/infernal_imp.gd") as GDScript
        ID.GREEDY_GOBLIN:
            return load("res://card_game/playing_card/cards/greedy_goblin.gd") as GDScript
        ID.ANCIENT_DEMON:
            return load("res://card_game/playing_card/cards/ancient_demon.gd") as GDScript
        ID.AGARIC_TURTLE:
            return load("res://card_game/playing_card/cards/agaric_turtle.gd") as GDScript
        ID.REPLACEABLE_PARTS:
            return load("res://card_game/playing_card/cards/replaceable_parts.gd") as GDScript
        ID.PET_COWN:
            return load("res://card_game/playing_card/cards/pet_cown.gd") as GDScript
        ID.LIBRARY_OF_ALEXANDRIA:
            return load("res://card_game/playing_card/cards/library_of_alexandria.gd") as GDScript
        ID.CLOWN_NOSE:
            return load("res://card_game/playing_card/cards/clown_nose.gd") as GDScript
        ID.PACIFIER:
            return load("res://card_game/playing_card/cards/pacifier.gd") as GDScript
        ID.CHICK_INATOR:
            return load("res://card_game/playing_card/cards/chick_inator.gd") as GDScript
        ID.BRAINWASHING_RAY:
            return load("res://card_game/playing_card/cards/brainwashing_ray.gd") as GDScript
        ID.NO_HONK_ZONE:
            return load("res://card_game/playing_card/cards/no_honk_zone.gd") as GDScript
        ID.SILENT_CLOWN:
            return load("res://card_game/playing_card/cards/silent_clown.gd") as GDScript
        ID.FOREMAN:
            return load("res://card_game/playing_card/cards/foreman.gd") as GDScript
        ID.CULTIST:
            return load("res://card_game/playing_card/cards/cultist.gd") as GDScript
        ID.BEEKEEPER:
            return load("res://card_game/playing_card/cards/beekeeper.gd") as GDScript
        ID.GREENER_PASTURES:
            return load("res://card_game/playing_card/cards/greener_pastures.gd") as GDScript
        ID.SPIKY_SHELL:
            return load("res://card_game/playing_card/cards/spiky_shell.gd") as GDScript
        ID.SHELL_POLISHING:
            return load("res://card_game/playing_card/cards/shell_polishing.gd") as GDScript
        ID.BERRY:
            return load("res://card_game/playing_card/cards/berry.gd") as GDScript
        ID.CHRIS_COGSWORTH:
            return load("res://card_game/playing_card/cards/chris_cogsworth.gd") as GDScript
        ID.STINGER_SWARM:
            return load("res://card_game/playing_card/cards/stinger_swarm.gd") as GDScript
        ID.HIVEMIND:
            return load("res://card_game/playing_card/cards/hivemind.gd") as GDScript
        ID.EXTENDED_WARRANTY:
            return load("res://card_game/playing_card/cards/extended_warranty.gd") as GDScript
        ID.NINJA_MASK:
            return load("res://card_game/playing_card/cards/ninja_mask.gd") as GDScript
        ID.LAUGHING_GAS:
            return load("res://card_game/playing_card/cards/laughing_gas.gd") as GDScript
        ID.INVASIVE_PARASITES:
            return load("res://card_game/playing_card/cards/invasive_parasites.gd") as GDScript
        ID.METAL_CHICKEN:
            return load("res://card_game/playing_card/cards/metal_chicken.gd") as GDScript
        ID.DESTRUCTION_TANK:
            return load("res://card_game/playing_card/cards/destruction_tank.gd") as GDScript
        ID.WIMPY:
            return load("res://card_game/playing_card/cards/wimpy.gd") as GDScript
        ID.WIMPY_SMASH:
            return load("res://card_game/playing_card/cards/wimpy_smash.gd") as GDScript
        ID.BULL_MARKET:
            return load("res://card_game/playing_card/cards/bull_market.gd") as GDScript
        ID.HYPERACTIVE_BEE:
            return load("res://card_game/playing_card/cards/hyperactive_bee.gd") as GDScript
        ID.GREEN_RANGER:
            return load("res://card_game/playing_card/cards/green_ranger.gd") as GDScript
        ID.ICE_MOTH:
            return load("res://card_game/playing_card/cards/ice_moth.gd") as GDScript
        ID.FORBIDDEN_FRUIT:
            return load("res://card_game/playing_card/cards/forbidden_fruit.gd") as GDScript
        ID.CYBERNETIC_ENHANCEMENT:
            return load("res://card_game/playing_card/cards/cybernetic_enhancement.gd") as GDScript
        ID.SHELL_SHIELD:
            return load("res://card_game/playing_card/cards/shell_shield.gd") as GDScript
        ID.TOXIC_SPORES:
            return load("res://card_game/playing_card/cards/toxic_spores.gd") as GDScript
        ID.CIRCUS_TENT:
            return load("res://card_game/playing_card/cards/circus_tent.gd") as GDScript
        ID.POISON_CLOUD:
            return load("res://card_game/playing_card/cards/poison_cloud.gd") as GDScript
        ID.POLLINATION:
            return load("res://card_game/playing_card/cards/pollination.gd") as GDScript
        _:
            push_warning("Invalid ID value: %d" % n)
            return null


static func get_entity(n: int):
    return get_entity_script(n).new()

static func get_all_ids() -> Array:
    return range(173)
