## THIS FILE WAS GENERATED BY AN AUTOMATED RUBY TASK!
## ANY MODIFICATIONS MADE TO THIS FILE MAY BE OVERWRITTEN!

class_name PlayingCardCodex
extends Node

enum ID {
    NULL_MINION = 0,
    MUSHROOM_MAN = 1,
    POT_OF_LINGUINE = 2,
    SPIKY_MUSHROOM_MAN = 3,
    TINY_TURTLE = 4,
    ZANY_ZOMBIE = 5,
    TRIANGLE_TROOPER = 6,
    SERGEANT_SQUARE = 7,
    RHOMBUS_RANGER = 8,
    PENTAGON_PROTECTOR = 9,
    CAPTAIN_CIRCLE = 10,
}

static func get_entity_script(n: int) -> GDScript:
    match n:
        ID.NULL_MINION:
            return load("./card_game/playing_card/cards/null_minion.gd") as GDScript
        ID.MUSHROOM_MAN:
            return load("./card_game/playing_card/cards/mushroom_man.gd") as GDScript
        ID.POT_OF_LINGUINE:
            return load("./card_game/playing_card/cards/pot_of_linguine.gd") as GDScript
        ID.SPIKY_MUSHROOM_MAN:
            return load("./card_game/playing_card/cards/spiky_mushroom_man.gd") as GDScript
        ID.TINY_TURTLE:
            return load("./card_game/playing_card/cards/tiny_turtle.gd") as GDScript
        ID.ZANY_ZOMBIE:
            return load("./card_game/playing_card/cards/zany_zombie.gd") as GDScript
        ID.TRIANGLE_TROOPER:
            return load("./card_game/playing_card/cards/triangle_trooper.gd") as GDScript
        ID.SERGEANT_SQUARE:
            return load("./card_game/playing_card/cards/sergeant_square.gd") as GDScript
        ID.RHOMBUS_RANGER:
            return load("./card_game/playing_card/cards/rhombus_ranger.gd") as GDScript
        ID.PENTAGON_PROTECTOR:
            return load("./card_game/playing_card/cards/pentagon_protector.gd") as GDScript
        ID.CAPTAIN_CIRCLE:
            return load("./card_game/playing_card/cards/captain_circle.gd") as GDScript
        _:
            push_warning("Invalid ID value: %d" % n)
            return null


static func get_entity(n: int):
    return get_entity_script(n).new()
